### ISSUE TITLE
论文中的一些疑惑

### ISSUE THREAD

**Issue by songyonger** [ShangHua-Gao/RBN#3]
您好，感谢您的工作！论文里的一些地方我没有明白，希望您能解答一下，谢谢。
①
![image](https://user-images.githubusercontent.com/46994308/116837906-dba50500-abfe-11eb-96ad-385fd9952905.png)
When the Km in Eqn.(5) is set to Uc，the running mean of Km is equal to E(X)
请问这句话应该怎么理解呢？
②在Choice of Instance Statistics中，你提到的the mean and standard division over spatial dimensions, denoted by 
![image](https://user-images.githubusercontent.com/46994308/116838030-7b629300-abff-11eb-9542-cfb3423827d9.png)
请问这两个值具体怎么计算？
③ ”Since scaling calibration only restricts the feature intensity while not changing the amount of information, scaling with both channel and spatial statistics results in a similar performance.”，请问改变信息的数量是什么意思呢？

**Comment by gasvn** [comment]
抱歉因为邮件太多没有看到你的问题
1. 因为km可以根据任务需求去调整，在推导的时候我们用了km=uc 这个case来说明(见 eq.2)，这时候，E(x)是uc的running mean（见eq.3）
2. 指的是计算某个pixel在不同channel上计算均值方差
3. 没改变信息量指的是特征只是经过缩放儿没有经过relu这样的函数把某些特征删除掉。

如果有其他问题欢迎询问。
